test:
  image: docker
  before_script:
    - apk add make
    - apk add bash
    - apk add python3
    - apk --update add 'py-pip' && pip install 'docker-compose'
    - make dynamic_ports
    - make containers_clean
    - make containers_build
    - make containers_start
  script:
    - make tests_ci
