test:
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  before_script:
    - apk add make
    - apk add bash
    - apk add python3
    - apk --update add 'py-pip'
    - pip install 'docker-compose==1.23.2'
  script:
    - make dynamic_ports
    - make containers_clean
    - make containers_build
    - make containers_start
    - make tests_ci
  after_script:
    - make containers_build
