test:
  image: docker
  before_script:
    - apk add make
    - apk add bash
    - apk add python3
    - apk add libffi-dev
    - apk add openssl-dev
    - apk --update add 'py-pip'
    - pip install 'docker-compose'
  script:
    - make dynamic_ports
    - make containers_clean
    - make containers_build
    - make containers_start
    - make tests_ci
  after_script:
    - make containers_build
