version: '3'
services:

    db:
        container_name: globomap_db
        image: arangodb:3.3.4
        ports:
            - "${GMAP_DB_PORT}:8529"
        environment:
            - ARANGO_NO_AUTH=1
        volumes:
            - globomap_db_vol:/var/lib/arangodb-apps/_db
        networks:
            - globomap_net
    api:
        container_name: globomap_api
        build:
            context: ./
            dockerfile: scripts/docker/Dockerfile
        ports:
            - "${GMAP_API_PORT}:5000"
            - "${GMAP_API_DEBUG_PORT}:5001"
        env_file:
            - scripts/docker/globomap.env
        volumes:
            - .:/app
            - ./scripts/docker/meta_collections.sh:/home/meta_collections.sh:ro
        networks:
            - globomap_net
        external_links:
            - db:globomap_db
            - keystone:globomap_keystone

    keystone:
        container_name: globomap_keystone
        image: krystism/openstack-keystone
        ports:
            - "${GMAP_KS_ADM_PORT}:35357"
            - "${GMAP_KS_PORT}:5000"
        restart: always
        environment:
            OS_TENANT_NAME: admin
            OS_USERNAME: admin
            # OS_PASSWORD: secret_admin_pass
        volumes:
            - ./scripts/docker/keystone.sh:/home/keystone.sh:ro
        networks:
            - globomap_net

    redis:
        container_name: globomap_redis
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
        ports:
            - "${GMAP_REDIS_PORT}:6379"
        networks:
            - globomap_net
        volumes:
            - globomap_redis_vol:/data

volumes:
    globomap_db_vol:
    globomap_redis_vol:

networks:
    globomap_net:
