version: '3'
services:

    db:
        container_name: globomap_db
        image: arangodb:3.1.23
        ports:
            - "8529:8529"
        environment:
            - ARANGO_NO_AUTH=1
        volumes:
            - globomap_db_vol:/var/lib/arangodb-apps/_db
        networks:
            - globomap_net

    queue:
        container_name: globomap_queue
        image: rabbitmq:3.6.9
        ports:
            - "5672"
            - "15672"
        networks:
            - globomap_net

    api:
        container_name: globomap_api
        build: .
        ports:
            - "5000:5000"
            - "5001:5001"
        env_file:
            - globomap.env
        volumes:
            - .:/app
        networks:
            - globomap_net
        command: make run
        depends_on:
            - db
            - queue
        links:
            - db:globomap_db
        external_links:
            - queue:globomap_queue

volumes:
    globomap_db_vol:

networks:
    globomap_net:
