version: '3'
services:

    db:
        container_name: globomap_db
        image: arangodb:3.3.4
        ports:
            - "8529:8529"
        environment:
            - ARANGO_NO_AUTH=1
        volumes:
            - globomap_db_vol:/var/lib/arangodb-apps/_db
        networks:
            - globomap_net
    api:
        container_name: globomap_api
        build:
            context: ./
            dockerfile: scripts/docker/Dockerfile
        ports:
            - "5000:5000"
            - "5001:5001"
        env_file:
            - scripts/docker/globomap.env
        volumes:
            - .:/app
        networks:
            - globomap_net
        command: make run
        depends_on:
            - db
        links:
            - db:globomap_db
        external_links:
            - keystone:globomap_keystone

    keystone:
        container_name: globomap_keystone
        image: krystism/openstack-keystone
        ports:
            - "35357:35357"
            - "5009:5000"
        restart: always
        environment:
            OS_TENANT_NAME: admin
            OS_USERNAME: admin
            # OS_PASSWORD: secret_admin_pass
        command:
             - /home/keystone.sh
        volumes:
            - ./scripts/docker/keystone.sh:/home/keystone.sh:ro
        networks:
            - globomap_net

    redis:
        container_name: globomap_redis
        image: redis:4.0.5-alpine
        command: ["redis-server", "--appendonly", "yes", "--requirepass", "password"]
        ports:
            - "6379:6379"
        networks:
            - globomap_net
        volumes:
            - globomap_redis_vol:/data

volumes:
    globomap_db_vol:
    globomap_redis_vol:

networks:
    globomap_net:
